version: '3.9'

services:
  django-app:
    container_name: django-app
    image: my-django-app
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      SECRET_KEY: "your-secret-key"
      DATABASE_URL: "postgres://admin:admin123@db:5432/monitoring"
      ALLOWED_HOSTS: "127.0.0.1,localhost"
    depends_on:
      - db

  django-db:
    container_name: django-db
    image: postgres:13
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
