# Generated by Django 5.0.6 on 2024-06-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_delete_programmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fullname',
        ),
        migrations.AddField(
            model_name='customer',
            name='preapproved_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
