# Generated by Django 5.0.6 on 2024-06-01 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customer_fullname_customer_preapproved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=60, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('score', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.PositiveSmallIntegerField()),
                ('contract_version', models.CharField(max_length=30)),
                ('maximum_payment_date', models.DateTimeField()),
                ('take_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.customer')),
            ],
        ),
    ]
