# Generated by Django 5.0.6 on 2024-06-01 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.loan')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.payment')),
            ],
        ),
    ]
