# Generated by Django 5.0.6 on 2024-06-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_paymentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Activo'), (3, 'rechazado'), (4, 'Pagado')], default=1),
        ),
    ]
