# Generated by Django 5.0.6 on 2024-06-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customer_status_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Completado'), (2, 'Rechazado')], default=1),
        ),
    ]
