# Generated by Django 5.0.6 on 2024-06-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_paymentbycustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentByCustomer',
        ),
    ]
