# Generated by Django 5.0.6 on 2024-06-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_paymentbycustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Activo'), (3, 'Rechazado'), (4, 'Pagado')], default=2),
        ),
    ]
